CREATE TABLE TF_DEPARTMENT
(
    ID NUMBER PRIMARY KEY,
    DEPTNO NUMBER NOT NULL UNIQUE,
    NAME VARCHAR2(60) NOT NULL,
    PARENT_DEPARTMENT_ID NUMBER,
    CREATED_AT DATE,
    STARTED_AT DATE,
    UPDATED_AT DATE,
    
    CONSTRAINT TF_DEPARTMENT_PARENT_DEPARTMENT_ID FOREIGN KEY (PARENT_DEPARTMENT_ID) REFERENCES TF_DEPARTMENT(ID)
);

CREATE SEQUENCE SEQ_TF_DEPARTMENT_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;


CREATE TABLE TF_USER
(
    EMPNO NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(60) NOT NULL,
    PASSWORD VARCHAR2(60) NOT NULL,
    NAME VARCHAR2(60),
    POSITION VARCHAR2(60),
    DEPARTMENT_ID NUMBER NOT NULL,
    STATUS VARCHAR2(60),
    STARTED_AT DATE,
    CREATED_AT DATE,
    UPDATED_AT DATE,
    
     CONSTRAINT TF_USER_FK_DEPARTMENT_ID FOREIGN Key(DEPARTMENT_ID) REFERENCES TF_DEPARTMENT (ID)
);

CREATE TABLE TF_ROLE
(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(60) NOT NULL
);


CREATE SEQUENCE SEQ_TF_ROLE_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_USER_ROLE
(
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    CREATED_AT DATE,
    
    CONSTRAINT TF_USER_ROLE_USER_ID FOREIGN KEY(USER_ID) REFERENCES TF_USER (EMPNO),
    CONSTRAINT TF_USER_ROLE_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES TF_ROLE (ID)
);

CREATE SEQUENCE SEQ_TF_USER_ROLE_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_PROJECT
(
    ID NUMBER PRIMARY KEY,
    OWNER_USER_ID NUMBER NOT NULL,
    NAME VARCHAR2(60) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR2(60),
    CREATED_AT DATE,
    UPDATED_AT DATE,
    
    CONSTRAINT TF_PROJECT_OWNER_USER_ID FOREIGN KEY(OWNER_USER_ID) REFERENCES TF_USER (EMPNO)
);

CREATE SEQUENCE SEQ_TF_PROJECT_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_PROJECT_MEMBER
(
    ID NUMBER PRIMARY KEY,
    PROJECT_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    PROJECT_ROLE VARCHAR2(60) DEFAULT 'MEMBER' NOT NULL ,
    STATUS VARCHAR2(60) DEFAULT 'ONGOING' NOT NULL ,
    JOINED_AT DATE,
    CREATED_AT DATE,
    
    CONSTRAINT TF_PROJECT_MEMBER_PROJECT_ID FOREIGN KEY(PROJECT_ID) REFERENCES TF_PROJECT (ID),
    CONSTRAINT TF_PROJECT_MEMBER_USER_ID FOREIGN KEY(USER_ID) REFERENCES TF_USER (EMPNO)
);

CREATE SEQUENCE SEQ_TF_PROJECT_MEMBER_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_TASK
(
    ID NUMBER PRIMARY KEY,
    PROJECT_ID NUMBER NOT NULL,
    PARENT_TASK_ID NUMBER,
    NAME VARCHAR2(60) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    STATUS VARCHAR2(60) DEFAULT 'TODO' NOT NULL,
    PRIORITY VARCHAR2(60) DEFAULT 'MEDIUM' NOT NULL,
    START_DATE DATE,
    DUE_DATE DATE,
    PROGRESS_PERCENT NUMBER CHECK (PROGRESS_PERCENT BETWEEN 0 AND 100),
    CREATED_AT DATE,
    UPDATED_AT DATE,
    
    CONSTRAINT TF_TASK_PROJECT_ID FOREIGN KEY(PROJECT_ID) REFERENCES TF_PROJECT (ID),
    CONSTRAINT TF_TASK_PARENT_TASK_ID FOREIGN KEY (PARENT_TASK_ID) REFERENCES TF_TASK(ID)
);

CREATE SEQUENCE SEQ_TF_TASK_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_TASK_ASSIGNEE
(
    ID NUMBER PRIMARY KEY,
    TASK_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    STATUS VARCHAR2(60) DEFAULT 'ONGOING' NOT NULL,
    JOINED_AT DATE,
    
    CONSTRAINT TF_TASK_ASSIGNEE_TASK_ID FOREIGN KEY(TASK_ID) REFERENCES TF_TASK(ID),
    CONSTRAINT TF_TASK_ASSIGNEE_USER_ID FOREIGN KEY(USER_ID) REFERENCES TF_USER(EMPNO)
);

CREATE SEQUENCE SEQ_TF_TASK_ASSIGNEE_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_TASK_STATUS_HISTORY
(
    ID NUMBER PRIMARY KEY,
    TASK_ID NUMBER NOT NULL,
    FROM_STATUS VARCHAR2(60),
    TO_STATUS VARCHAR2(60) NOT NULL,
    CHANGED_BY NUMBER NOT NULL,
    CHANGED_AT DATE,
    MEMO VARCHAR2(4000),
  
    CONSTRAINT TF_TASK_STATUS_HISTORY_TASK_ID FOREIGN KEY(TASK_ID) REFERENCES TF_TASK(ID),
    CONSTRAINT TF_TASK_STATUS_HISTORY_CHANGED_BY FOREIGN KEY(CHANGED_BY) REFERENCES TF_USER(EMPNO)
);

CREATE SEQUENCE SEQ_TF_TASK_STATUS_HISTORY_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_CALENDAR_EVENT
(
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    PROJECT_ID NUMBER,
    TASK_ID NUMBER,
    NAME VARCHAR2(60) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    TYPE VARCHAR2(60) DEFAULT 'TASK' NOT NULL,
    CREATED_AT DATE,
    UPDATED_AT DATE,
    
    CONSTRAINT TF_CALENDAR_EVENT_USER_ID FOREIGN KEY(USER_ID) REFERENCES TF_USER(EMPNO),
    CONSTRAINT TF_CALENDAR_EVENT_PROJECT_ID FOREIGN KEY(PROJECT_ID) REFERENCES TF_PROJECT(ID),
    CONSTRAINT TF_CALENDAR_EVENT_TASK_ID FOREIGN KEY(TASK_ID) REFERENCES TF_TASK(ID)
);

CREATE SEQUENCE SEQ_TF_CALENDAR_EVENT_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_BOARD
(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(60) NOT NULL,
    PROJECT_ID NUMBER,
    CREATED_AT DATE,
    
    CONSTRAINT TF_BOARD_PROJECT_ID FOREIGN KEY(PROJECT_ID) REFERENCES TF_PROJECT(ID)
);

CREATE SEQUENCE SEQ_TF_BOARD_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_POST
(
    ID NUMBER PRIMARY KEY,
    BOARD_ID NUMBER NOT NULL,
    AUTHOR_USER_ID NUMBER NOT NULL,
    TITLE VARCHAR2(1000) NOT NULL,
    CONTENT VARCHAR2(4000),
    CREATED_AT DATE,
    UPDATED_AT DATE,
    
    CONSTRAINT TF_POST_BOARD_ID FOREIGN KEY(BOARD_ID) REFERENCES TF_BOARD(ID),
    CONSTRAINT TF_POST_AUTHOR_USER_ID FOREIGN KEY(AUTHOR_USER_ID) REFERENCES TF_USER(EMPNO)
);

CREATE SEQUENCE SEQ_TF_POST_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_COMMENT
(
    ID NUMBER PRIMARY KEY,
    POST_ID NUMBER NOT NULL,
    AUTHOR_USER_ID NUMBER NOT NULL,
    PARENT_COMMENT_ID NUMBER,
    CONTENT VARCHAR2(4000) NOT NULL,
    CREATED_AT DATE,
    UPDATED_AT DATE,
    
    CONSTRAINT TF_COMMENT_POST_ID FOREIGN KEY(POST_ID) REFERENCES TF_POST(ID),
    CONSTRAINT TF_COMMENT_AUTHOR_USER_ID FOREIGN KEY(AUTHOR_USER_ID) REFERENCES TF_USER(EMPNO),
    CONSTRAINT TF_COMMENT_PARENT_COMMENT_ID FOREIGN KEY (PARENT_COMMENT_ID) REFERENCES TF_COMMENT(ID)
);

CREATE SEQUENCE SEQ_TF_COMMENT_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE TF_ATTACHMENT
(
    ID NUMBER PRIMARY KEY,
    UPLOADER_USER_ID NUMBER NOT NULL,
    POST_ID NUMBER,
    TASK_ID NUMBER,
    FILE_NAME VARCHAR2(4000) NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR2(4000),
    FILE_URL VARCHAR2(4000),
    CREATED_AT DATE,
    
    CONSTRAINT TF_ATTACHMENT_UPLOADER_USER_ID FOREIGN KEY(UPLOADER_USER_ID) REFERENCES TF_USER(EMPNO),
    CONSTRAINT TF_ATTACHMENT_POST_ID FOREIGN KEY(POST_ID) REFERENCES TF_POST(ID),
    CONSTRAINT TF_ATTACHMENT_TASK_ID FOREIGN KEY(TASK_ID) REFERENCES TF_TASK(ID)
);

CREATE SEQUENCE SEQ_TF_ATTACHMENT_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;   
    
CREATE TABLE TF_ISSUE
(
    ID NUMBER PRIMARY KEY,
    PROJECT_ID NUMBER NOT NULL,
    TASK_ID NUMBER,
    REPORTER_USER_ID NUMBER NOT NULL,
    TITLE VARCHAR2(1000) NOT NULL,
    CONTENT VARCHAR2(4000),
    STATUS VARCHAR2(60) DEFAULT 'UNREAD' NOT NULL,
    CREATED_AT DATE,
    UPDATED_AT DATE,
    
    CONSTRAINT TF_ISSUE_PROJECT_ID FOREIGN KEY(PROJECT_ID) REFERENCES TF_PROJECT(ID),
    CONSTRAINT TF_ISSUE_TASK_ID FOREIGN KEY(TASK_ID) REFERENCES TF_TASK(ID),
    CONSTRAINT TF_ISSUE_REPORTER_USER_ID FOREIGN KEY(REPORTER_USER_ID) REFERENCES TF_USER(EMPNO)
);

CREATE SEQUENCE SEQ_TF_ISSUE_PK
START WITH 1
INCREMENT BY 1
NOCYCLE; 

CREATE TABLE TF_NOTIFICATION
(
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TYPE VARCHAR2(60) NOT NULL,
    MESSAGE VARCHAR2(4000) NOT NULL,
    LINK_URL VARCHAR2(4000),
    IS_READ VARCHAR2(60) DEFAULT 'UNREAD' NOT NULL,
    CREATED_AT DATE,
    
    CONSTRAINT TF_NOTIFICATION_USER_ID FOREIGN KEY(USER_ID) REFERENCES TF_USER(EMPNO)
);

CREATE SEQUENCE SEQ_TF_NOTIFICATION_PK
START WITH 1
INCREMENT BY 1
NOCYCLE; 

CREATE TABLE TF_REPORT
(
    ID NUMBER PRIMARY KEY,
    PROJECT_ID NUMBER NOT NULL,
    AUTHOR_USER_ID NUMBER NOT NULL,
    PERIOD_TYPE VARCHAR2(60) NOT NULL,
    PERIOD_START DATE NOT NULL,
    PERIOD_END DATE NOT NULL,
    SUMMARY VARCHAR2(4000),
    CREATED_AT DATE,
    
    CONSTRAINT TF_REPORT_PROJECT_ID FOREIGN KEY(PROJECT_ID) REFERENCES TF_PROJECT(ID),
    CONSTRAINT TF_REPORT_AUTHOR_USER_ID FOREIGN KEY(AUTHOR_USER_ID) REFERENCES TF_USER(EMPNO)
);
    
CREATE SEQUENCE SEQ_TF_REPORT_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;


    